---
- name: Install jq on Ubuntu systems
  hosts: all
  become: yes
  gather_facts: yes    

  tasks:
    - name: Install jq if OS is Ubuntu
      apt:
        name: jq
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian" and
            ansible_facts['distribution'] == "Ubuntu"
